### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by apm1007** [amcolash/MMM-GoogleFit#8] opened 2018-05-02 20:12 UTC
Hi, at first let me say thanks for this great module.
i got an display error since updating to latest magic mirror version.
![grafik](https://user-images.githubusercontent.com/11927080/39546802-e6b6f1b0-4e55-11e8-855f-bb668120ff3b.png)
Picture is attached. Any idea how to fix this?

**Comment by amcolash** [comment] 2018-05-02 23:40
Not quite sure what the issue is, but I am looking into it. This is a duplicate of #7 so I am going to close this issue out.

**Closed by amcolash** 2018-05-02 23:40 UTC
